### PR TITLE
Fixes #30911 - Fix issue with selecting host ids for Upgrade Button

### PR DESCRIPTION
**Pull request by stejskalleos**
**How to reproduce issue**
* Preupgrade job without any items that can be fixed by Leapp tool (without commands)
* At _Leapp preupgrade report_ tab, click on _Run Upgrade_ button

After redirect _Search Query_ on Job invocation form is empty.

**Fix**
Not using `idsForInvocationFromReports`.

### CODE REVIEW

**Comment by xprazak2** [comment]
Works as expected. Linting issues unrelated, though github will not allow me to merge without required check. 

@stejskalleos, could you rename `props` to `componentProps` on lines 113, 114, 129 in `PreupgradeReports.js` please? That should make the lint green.

**Comment by stejskalleos** [comment]
`lint` issues fixed.
@adamruzicka If you okay with PR we can merge & I'll release new pkg version ASAP.

**Review by adamruzicka — APPROVED** [review]
Makes sense, ACK

**Comment by adamruzicka** [comment]
Thank you @stejskalleos & @xprazak2 !

**Pull request merged**
