### PR TITLE
Support Ruby 2.7 and update version of @theforeman

### PR DESCRIPTION
**Pull request by stejskalleos**
See:
https://community.theforeman.org/t/ruby-2-7-moving-rpm-deployments-to-ruby-2-7/22734

### CODE REVIEW

**Comment by adamruzicka** [comment]
Seems to work fine. From what I've seen most plugins test against node 12, with some testing against node 10 in addition to that. Let's drop testing against node 8.

**Comment by stejskalleos** [comment]
We can drop 8 version, it's not supported anyway: https://nodejs.org/en/about/releases/

**Review by adamruzicka — APPROVED** [review]
ACK

**Comment by adamruzicka** [comment]
Thank you @stejskalleos !

**Pull request merged**
