### PR TITLE
Fixes #38073 - Support Rails 7.0

### PR DESCRIPTION
**Pull request by ofedoren**
Alternative for https://github.com/theforeman/foreman_leapp/pull/142.

Tested with Rails 7, seems to be working, although I'd want to ask a maintainer to actually check plugin's workflow live.

Locally tests are green, but they don't seem to always catch issues.

The changes here should be 6.1 compatible, thus doesn't require Rails 7 PR.

### CODE REVIEW

**Comment by ofedoren** [comment]
Rebased on 5e01e5dcb862893c1108b29cb107993d11d4cc0e

**Comment by stejskalleos** [comment]
Rubocop is not happy :(

**Comment by ofedoren** [comment]
> Rubocop is not happy :(

I've disabled most-hated-by-me rule, please reconsider enabling it if it matters

**Review by stejskalleos — APPROVED** [review]
Changes LGTM: I haven't tested them myself, but they look safe.
Let's get this in.

**Pull request merged**
